class EventsController < ApplicationController

  def index
  end

  def create
    puts params
      # @Event = Event.new(paramsz
      Event.create(
        # user: user, -- This will be generated after the user signs into-the session  
        activity_date: params[:event_date_time], 
        notes: params[:event_note],
        eventable_type: params[:event_type].to_s,
        # eventable_id: 42, -- This will be generated by the database 
      )
    puts "Created #{Event.count} event(s) sucessfully."       
  end

end
